//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace otp.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("otp.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discard.
        /// </summary>
        internal static string btnDiscard {
            get {
                return ResourceManager.GetString("btnDiscard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request .
        /// </summary>
        internal static string btnRequest {
            get {
                return ResourceManager.GetString("btnRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmed.
        /// </summary>
        internal static string Confirmed {
            get {
                return ResourceManager.GetString("Confirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        internal static string cuAddress {
            get {
                return ResourceManager.GetString("cuAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cost.
        /// </summary>
        internal static string cuCost {
            get {
                return ResourceManager.GetString("cuCost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Price you set.
        /// </summary>
        internal static string cuCost2 {
            get {
                return ResourceManager.GetString("cuCost2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        internal static string cuDate {
            get {
                return ResourceManager.GetString("cuDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string cuDescriptions {
            get {
                return ResourceManager.GetString("cuDescriptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Of Customer.
        /// </summary>
        internal static string cuEmail {
            get {
                return ResourceManager.GetString("cuEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image Problem.
        /// </summary>
        internal static string cuImage {
            get {
                return ResourceManager.GetString("cuImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Name is:.
        /// </summary>
        internal static string cuName {
            get {
                return ResourceManager.GetString("cuName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Phone is:.
        /// </summary>
        internal static string cuPhone {
            get {
                return ResourceManager.GetString("cuPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About App.
        /// </summary>
        internal static string lblAboutApp {
            get {
                return ResourceManager.GetString("lblAboutApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        internal static string lblAddress {
            get {
                return ResourceManager.GetString("lblAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Area.
        /// </summary>
        internal static string lblArea {
            get {
                return ResourceManager.GetString("lblArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change.
        /// </summary>
        internal static string lblChange {
            get {
                return ResourceManager.GetString("lblChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do You Want To Change Your Password?.
        /// </summary>
        internal static string lblChangePass {
            get {
                return ResourceManager.GetString("lblChangePass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ChangePassword.
        /// </summary>
        internal static string lblChangePassword {
            get {
                return ResourceManager.GetString("lblChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ask AI.
        /// </summary>
        internal static string lblChat {
            get {
                return ResourceManager.GetString("lblChat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ask Ai about Your Problem.
        /// </summary>
        internal static string lblChatAsk {
            get {
                return ResourceManager.GetString("lblChatAsk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose a Language .
        /// </summary>
        internal static string lblChooseLanguage {
            get {
                return ResourceManager.GetString("lblChooseLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        internal static string lblCity {
            get {
                return ResourceManager.GetString("lblCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cost.
        /// </summary>
        internal static string lblCost {
            get {
                return ResourceManager.GetString("lblCost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string lblDescription {
            get {
                return ResourceManager.GetString("lblDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string lblEmail {
            get {
                return ResourceManager.GetString("lblEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        internal static string lblHome {
            get {
                return ResourceManager.GetString("lblHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        internal static string lblHome1 {
            get {
                return ResourceManager.GetString("lblHome1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        internal static string lblHome11 {
            get {
                return ResourceManager.GetString("lblHome11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string lblLanguage {
            get {
                return ResourceManager.GetString("lblLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string lblLanguage1 {
            get {
                return ResourceManager.GetString("lblLanguage1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LogOut.
        /// </summary>
        internal static string lblLogOut {
            get {
                return ResourceManager.GetString("lblLogOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu.
        /// </summary>
        internal static string lblMenu {
            get {
                return ResourceManager.GetString("lblMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu.
        /// </summary>
        internal static string lblMenu1 {
            get {
                return ResourceManager.GetString("lblMenu1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu.
        /// </summary>
        internal static string lblMenu11 {
            get {
                return ResourceManager.GetString("lblMenu11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your New Password.
        /// </summary>
        internal static string lblNewPassword {
            get {
                return ResourceManager.GetString("lblNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orders.
        /// </summary>
        internal static string lblOrders {
            get {
                return ResourceManager.GetString("lblOrders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orders.
        /// </summary>
        internal static string lblOrders1 {
            get {
                return ResourceManager.GetString("lblOrders1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orders.
        /// </summary>
        internal static string lblOrders11 {
            get {
                return ResourceManager.GetString("lblOrders11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone:.
        /// </summary>
        internal static string lblPhoneNumber {
            get {
                return ResourceManager.GetString("lblPhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pic Image For Problem.
        /// </summary>
        internal static string lblPicImage {
            get {
                return ResourceManager.GetString("lblPicImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        internal static string lblProfile {
            get {
                return ResourceManager.GetString("lblProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        internal static string lblProfile1 {
            get {
                return ResourceManager.GetString("lblProfile1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        internal static string lblProfile11 {
            get {
                return ResourceManager.GetString("lblProfile11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity.
        /// </summary>
        internal static string lblQty {
            get {
                return ResourceManager.GetString("lblQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rate.
        /// </summary>
        internal static string lblrate {
            get {
                return ResourceManager.GetString("lblrate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requests.
        /// </summary>
        internal static string lblRequests {
            get {
                return ResourceManager.GetString("lblRequests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request Service.
        /// </summary>
        internal static string lblRequestService {
            get {
                return ResourceManager.GetString("lblRequestService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Your Password.
        /// </summary>
        internal static string lblReset {
            get {
                return ResourceManager.GetString("lblReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string lblResetEmail {
            get {
                return ResourceManager.GetString("lblResetEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Password.
        /// </summary>
        internal static string lblResetPassword {
            get {
                return ResourceManager.GetString("lblResetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Provider.
        /// </summary>
        internal static string lblSelectProvider {
            get {
                return ResourceManager.GetString("lblSelectProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Services.
        /// </summary>
        internal static string lblServices {
            get {
                return ResourceManager.GetString("lblServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string lblSetting {
            get {
                return ResourceManager.GetString("lblSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share.
        /// </summary>
        internal static string lblShare {
            get {
                return ResourceManager.GetString("lblShare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terms &amp; Conditions.
        /// </summary>
        internal static string lblTerms {
            get {
                return ResourceManager.GetString("lblTerms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome.
        /// </summary>
        internal static string lblWelcome {
            get {
                return ResourceManager.GetString("lblWelcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name of Provider.
        /// </summary>
        internal static string providerName {
            get {
                return ResourceManager.GetString("providerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rate Provider.
        /// </summary>
        internal static string rate {
            get {
                return ResourceManager.GetString("rate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update .
        /// </summary>
        internal static string Rejected {
            get {
                return ResourceManager.GetString("Rejected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty List Of Requests.
        /// </summary>
        internal static string txtemptyRequest {
            get {
                return ResourceManager.GetString("txtemptyRequest", resourceCulture);
            }
        }
    }
}
