//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webapp.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ServicesEntities : DbContext
    {
        public ServicesEntities()
            : base("name=ServicesEntities")
        {
            this.Configuration.LazyLoadingEnabled = false;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TableOfProvider> TableOfProviders { get; set; }
        public virtual DbSet<TbOfRequest> TbOfRequests { get; set; }
        public virtual DbSet<TbProvider> TbProviders { get; set; }
        public virtual DbSet<TbServiceProvider> TbServiceProviders { get; set; }
        public virtual DbSet<TbService> TbServices { get; set; }
        public virtual DbSet<TbUser> TbUsers { get; set; }
        public virtual DbSet<TbRating> TbRatings { get; set; }
        public virtual DbSet<VwRequestsProvider> VwRequestsProviders { get; set; }
        public virtual DbSet<VwServiceProvider> VwServiceProviders { get; set; }
        public virtual DbSet<VwServic> VwServics { get; set; }
    }
}
