//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webapp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VwServiceProvider
    {
        public int ProvicderId { get; set; }
        public string ProviderName { get; set; }
        public string Description { get; set; }
        public double Lat { get; set; }
        public double Long { get; set; }
        public string ImageName { get; set; }
        public Nullable<double> Rating { get; set; }
        public Nullable<double> ratting { get; set; }
        public Nullable<int> ServiceId { get; set; }
        public string Area { get; set; }
    }
}
